### ISSUE TITLE
AJAX

### ISSUE THREAD

**Issue by shshaw** [fabiospampinato/cash#103]
I haven't really used native `fetch` before, so I took a closer look and found that it's [not supported in Safari, IE or Edge](http://caniuse.com/#feat=fetch), which is a huge gap, and most of the recommended replacement libraries / polyfills are quite large.

Seeing as AJAX a common need ( #15, #99 ), it may be worthwhile to keep a simple AJAX method with IE9+ support using `XMLHttpRequest` & script for JSONP. 

I was able to work out a rough method that only weighs 1kb minified, 0.6kb gzipped, with a decent set of functionality. Is this something that would be worth integrating into cash and building some tests for or do we want to keep AJAX out?

POST request: http://jsfiddle.net/qfrqxgac/3/
GET & JSONP (CORS) request: http://codepen.io/shshaw/pen/QNxprm?editors=0010

http://httpbin.org/ would be a good resource for running tests.

```
function noop(){};

var ajaxOpts = {
      success: noop,
      error: noop,
      complete: noop,
      type: 'GET',
      async: true
    };

var uid = Date.now();
cash.guid = function(){
  return '_cash'+(uid++).toString(16);
};

cash.ajax = function(url,options) {

  if ( arguments.length === 1 ) {
    options = url;
    url = options.url;
  }

  if ( !url ) { return false; }

  options = cash.extend({},ajaxOpts,options);

  var request,
      queryData,
      callbackName;

  if ( options.dataType === 'jsonp' || options.dataType === 'script' ) {
    request = document.createElement('script');
    callbackName = cash.guid();

    options.data.callback = callbackName;
    window[callbackName] = function(data){
      options.success.call(request, data, null, request);
    };

    request.onload = request.onerror = function(e){ 
      if ( e && e.type === "error" ) {
        options.error.call(this, request);
      }
      options.complete.call(this, request);
      request.remove();
    }

    queryData = '?';
    for (var key in options.data){
      queryData += encodeURIComponent(key) + '=' + encodeURIComponent(options.data[key]) +'&';
    }

    request.src = url + queryData;
    document.head.appendChild(request);

  } else {
    request = new XMLHttpRequest();
    request.open(options.type, url, options.async);

    request.setRequestHeader("X-Requested-With","XMLHttpRequest");

    request.onload = request.onerror = function onload() {
      var text = request.statusText;
      if ( request.status >= 200 && request.status < 400 ) {
        var response = request.responseText;
        if ( options.dataType === 'json' ) { response = JSON.parse(response); }
        options.success.call(this, response, text, request);
      } else {
        options.error.call(this, request, text);
      }
      options.complete.call(this, request, text);
    };

    if ( options.data ) {
      queryData = cash.isString(options.data) ? options.data : JSON.stringify(options.data);
    }

    request.send( queryData );
  }

  return request;
};
```

**Comment by simeydotme** [comment]
Any way to maintain the chaining of `.done()`, `.fail()`, `.always()` ? ... guess it would require promises... which would require browser checks/polyfills... meh.

I still think using a library is better, because the user then has the choice of how big their codebase is. I also see that if we implemented this, then we'd have 100+ issues raised immediately with AJAX requests (ie: add more features, chainable callbacks (promises))

**Comment by shshaw** [comment]
`done`, `fail` and `always` shouldn't be too difficult to implement without Promises as they're basically just another way to do the `success`, `error` and `complete` callbacks, respectively. The `$.ajax` function could return a promise-like class that wraps the request with those methods on the prototype. I expect that will still be pretty lightweight overall.

I think that if we decide to include AJAX, we should set the limitations and document that in the README to prevent feature creep or tons of issues.

Alternatively, this could be a separate file (a plugin, if you will) so that users who don't need it don't get any bloat, and users who do want it have a familiar way to handle AJAX requests without learning a new library or adding another 10+kb to their codebase.

**Comment by shshaw** [comment]
Something along these lines:

```
function Request(url,options){
  ...
}

Request.prototype = {
  done: function(){},
  fail: function(){}
  always: function(){}
};

cash.ajax = function(url,options) {
  return new Request(url,options);
}
```

**Comment by simeydotme** [comment]
well, I'm not against a module that is separate to the core :) 
`cash.dom`, `cash.ajax` or something... but I would like to get the unit tests finished first so it can be properly covered :) Making some good progress on that front. We should get a gitter/slack channel so we can talk a bit easier.

**Comment by shshaw** [comment]
Absolutely. Unit testing will definitely be vital. AJAX isn't a high priority, but it seems to be functionality people would get use out of, whether it's a plugin/separate module or a part of the main library. 

Gitter/Slack could be worthwhile for larger planning. I don't have much experience with either, so I'm flexible if you or @kenwheeler would like to get something going.

**Comment by vivekimsit** [comment]
I am not in favor of adding Ajax since we already have well tested and robust libraries out there, isn't cash was supposed to handle dom and be lightweight?

**Comment by kenwheeler** [comment]
@shshaw @simeydotme @vivekimsit I agree with this sentiment. Fetch is polyfilled fantastically in current form. Outside of that, there are plenty of 3rd party libs that are great for ajax func. My vision of cash is, generally speaking, dom traversal, manipulation only. The only reason I would use jquery now is to query and operate on the DOM. Cash, in theory, should serve that need.

**Comment by shshaw** [comment]
@kenwheeler @simeydotme @vivekimsit I understand the desire to keep Cash DOM only, however AJAX is an action that's often heavily tied to the DOM (inserting additional content, submitting data from a form & showing a response, etc.).

Looking at the main polyfills / alternate libraries, you'll be adding at least 10kb to your codebase (more if the browser doesn't support promises), you're still having to learn another syntax, and fetch doesn't support JSONP by default, meaning yet another polyfill/library.

At the very least, we should consider providing a simple `$.ajax` wrapper for `fetch` with the familiar API, much like the rest of Cash provides a familiar API and convenient methods for modern browser functionality.

If `fetch` needs to be polyfilled (IE, Safari and mobile browsers), we can warn in the console, and could add simple JSONP support like [fetch-jsonp](https://github.com/camsong/fetch-jsonp/). All in all, this would likely be 1kb or less, and again could be provided as a separate module/plugin to keep the core Cash library light.

**Comment by teamgroove** [comment]
There is a polyfill for those old browsers. https://github.com/github/fetch
This polyfill is written as closely as possible to the standard Fetch specification at https://fetch.spec.whatwg.org.

**Comment by shshaw** [comment]
Yeah, I've looked at few polyfill options, @teamgroove. Problem is for most of these you still need a 30kb Promise Polyfill library for IE in addition to the Fetch polyfill, and I think IE9 is still left out in the cold.

**Comment by teamgroove** [comment]
It will only be polyfilled with conditional-comments, right? So - this 32kb payload will only hit the ones that deserved it :) </humor> 
IE10 should do it, or am i wrong? https://github.com/github/fetch/issues/129

**Comment by teamgroove** [comment]
Little off-topic, but the same kind of issue on the horizon, if we'd like to do ES6-promise. IE is by far not the benchmark for adding extra code into a lib. shim es6-promise: https://github.com/stefanpenner/es6-promise

**Comment by menangen** [comment]
Not necessary to increase the size of the library, in addition, the entire code for ajax - essentially sugar.

http://blog.garstasio.com/you-dont-need-jquery/ajax/

Best usecase is using something like Vue.js for UI and cash for other low level features and rest data loading into plain js objects. Vue.js has no model fetching from server and will be good use simple and clear api in cash for it.

**Comment by shshaw** [comment]
@menangen @teamgroove Yes, modern browsers have Fetch built in that works great and there are polyfills for adding that support in older browsers, but supporting all relevant browsers is a pain and requires a lot of knowledge from the developer on how to set that all up.

[There are a lot of major browsers do not support Fetch, like IE11-, Edge 13- and Safari 9-, and many of them would require the additional Promise polyfill](http://caniuse.com/#feat=promises,fetch). Several of those browsers don't support conditional comments, so you're looking at adding feature detection/conditional loading libraries to load the polyfilll. 

Cash is designed to make relatively simple tasks even easier with a common interface and helpful utilities. Using the code from youdontneedjquery.com is a lot to remember or setup for a lot of developers that just want a clear and easy API that works across browsers. There are other libraries that do AJAX requests, but that's just another dependency for developers to learn and integrate with Cash. Requiring external dependencies, conditional comments, and/or conditional loading to support a basic function isn't really simple and means a lot of bloat and setup on the developer's end.

The initial code I have posted is a small wrapper for XHR & JSONP requests, making it easy to create basic requests to fetch and post data all the way back to IE9 without any polyfills or external dependencies. It would be a separate file from Cash for users that need the functionality so it won't add any bloat, and developers that like Fetch are still free to use it and manage their own polyfills.

@kenwheeler Feel free to shut this down or confirm that AJAX is something worthwhile to add as a separate add-on. I've made my case for why AJAX would be valuable to have in the Cash toolkit, but it's ultimately your call.

**Comment by tommiehansen** [comment]
@shshaw Your last reply basically is the answer to why people still uses jQuery.

It works and is pretty reliable for all common tasks. I can't stress enough how important that is.

The problem with youdontneedjquery.com is that it completely ignores cross browser niggles and issues. Just because something **works** doesn't mean that it really **works** to a 100%. Often one has to be extremely aware of all current cross browser issues when doing native JS. For the most time one is fine but not always... This "not always" can steal a lot of hours and in a professional environment with 10k different users per day with different browsers, hardware etc etc etc one simply do not got the time.

**Comment by pwFoo** [comment]
Maybe  https://github.com/axios/axios or https://github.com/typicode/fetchival (smaller) as plugin?

**Comment by menangen** [comment]
I use native ‘fetch’ anywhere, also in Vue and Preact environment...with ‘await’ of course.

**Comment by pwFoo** [comment]
Because of compatibility to jQuery maybe some other solution would be better then axios or fetchival.
https://github.com/fdaciuk/ajax

**Comment by fabiospampinato** [comment]
I think we shouldn't add support for this if the API would be completely different from jQuery's implementation, in that case just include that other thing into your bundle along with cash.

I'm ok with including support for AJAX as a plugin, basically included in the repo but disabled by default in our bundles, that's basically a subset of what jQuery implements.

**Comment by DzigaV** [comment]
I signed up to Github solely to ask for basic $.get and $.post in Cash. Thank to you @fabiospampinato, this library is now in fantastic shape. So much so that we're going to use it in a new project. But AJAX is all that's necessary to make Cash a perfect, single-dependency framework for client-side development, and therefore a true jQuery replacement.

Please consider implementing it, in as few bytes as possible, naturally 😄

**Comment by fabiospampinato** [comment]
@DzigaV I'm personally using a modified version of [unfetch](https://github.com/developit/unfetch) that provides a similar API to `jQuery.ajax`, returns a fetch-like Response object, and implements a few other things I need, you might want to consider it maybe, you can find it [here](https://github.com/svelto/svelto/blob/master/src/lib/fetch/fetch.js).

I currently don't have the time nor the need for writing an ajax plugin for Cash, but if you want to submit any I'll be happy to consider it.

**Comment by teamgroove** [comment]
axios
https://github.com/axios/axios

**Comment by pwFoo** [comment]
After playing with fetch I would prefer a modern fetch() solution as plugin...
Works nice also with php $_POST if body is converted to FormData.

**Comment by SamyCookie** [comment]
There is already a lot of good fetch wrappers, (eg. https://github.com/elbywan/wretch).
I think another implementation in cash is not necessary to keep the Cash library simple and thin.

**Comment by pwFoo** [comment]
@SamyCookie 
Thanks for sharing wretch!  I have  to take a look :)

**Comment by volomike** [comment]
If you're looking for a super simple jQuery-like `$.get(url,options,callback)` or `$.post(url,options,callback)`, then I've implemented something like the following.

Credit: https://blog.garstasio.com/you-dont-need-jquery/ajax/

Just note that I don't handle anything except a 200 status. You can revise as you wish.

```
cash.json2query = function(o) {
  var q = '';
  if (o) {
    for (var key in o) {
      if (o.hasOwnProperty(key)) {
        q += encodeURIComponent(key) + '=' + encodeURIComponent(o[key]) +'&';
      }
    }
  }
  return q;
}

cash.get = function(url,options,callback) {
  var xhr = new XMLHttpRequest();
  if (options) {
    url += '?';
    url += $.json2query(options);
  }
  xhr.open('GET',url);
  xhr.onload = function() {
    if (xhr.status === 200) {
      callback(xhr.responseText);
    }
  }
  xhr.send();
}

cash.post = function(url,options,callback) {
  var xhr = new XMLHttpRequest();
  var data = '';
  if (options) {
    data = $.json2query(options);
  }
  xhr.open('POST',url);
  xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
  xhr.onload = function() {
    if (xhr.status === 200) {
      callback(xhr.responseText);
    }
  }
  xhr.send(data);
}
```

**Comment by visvxplore** [comment]
Add the script [https://polyfill.io/v3/polyfill.min.js?features=fetch](https://polyfill.io/v3/polyfill.min.js?features=fetch). Start writing your fetch. [Polyfill.io](https://polyfill.io) will automatically detect the browser and adds polyfill to [supported-browsers](https://polyfill.io/v3/supported-browsers/), if necessary.

**Comment by sideshot** [comment]
@fabiospampinato I really like the idea of cash. I also just researched unfetch and agree that might be the better way. Leave it separate. 500 bytes.

**Comment by fabiospampinato** [comment]
Closing as an official ajax plugin won't be written, use one of the suggested ones. If anybody knows of any plugin that's compatible with Cash and implements the same API as jQuery _well_ I'll link to it in the readme.
