### ISSUE TITLE
Ensuring `$.fn.hasClass` works on SVG elements in IE11

### ISSUE THREAD

**Issue by limonte** [fabiospampinato/cash#326]
`Unable to get property 'contains' of undefined or null reference` in IE11 because it appears IE11 does not support classList on SVG elements: https://caniuse.com/#feat=classlist 

That breaks `hasClass` (and possibly other methods using `classList`) for SVGs in IE11.

Code to reproduce the issue:

```js
const svg = $('<svg><path class="my-class"/></svg>')
svg.find('path').hasClass('another-class')
```

**Comment by fabiospampinato** [comment]
As the migration guide [points out](https://github.com/kenwheeler/cash/blob/master/docs/migration_guide.md#disconnected-nodes-iframes-and-svgs) Cash doesn't work with SVGs as well as jQuery does, I don't think it should be used for manipulating SVGDOMs. 

I think perhaps this has been broken since v4 or even v3 🤔

It'd be useful to understand what exactly works and in which browsers regarding SVGs, like what would it take to make Cash work with SVGs completely? 🤔

**Comment by limonte** [comment]
> As the migration guide points out Cash doesn't work with SVGs as well as jQuery does, I don't think it should be used for manipulating SVGDOMs.

I missed that part, sorry!

Feel free to close this issue with `wontfix` label because handling SVG elements can add quite a bit to the bundle size.

For my project, I override the `hasClass` method for my particular needs.

**Comment by fabiospampinato** [comment]
> Feel free to close this issue with wontfix label because handling SVG elements can add quite a bit to the bundle size.

Do you know what would need to be fixed in order to Cash to support SVGs fully?

**Comment by limonte** [comment]
> Do you know what would need to be fixed in order to Cash to support SVGs fully?

Nope, I solved my particular case, but I do not have a sufficient level of SVG knowledge.

**Comment by fabiospampinato** [comment]
@limonte could you post your patched `hasClass` method?

**Comment by limonte** [comment]
Sure, but my pathed method is dummy and covering only my small particular case :)

```js
$.fn.hasClass = function (this: Cash, cls: string): boolean {
  const el = this[0]
  if (!el) {
    return false
  }
  if (el.classList) {
    return el.classList.contains(cls)
  // IE11, SVG elements
  } else {
    return !!this.get(0)?.getAttribute('class')?.match(cls)
  }
}
```

**Comment by limonte** [comment]
R.I.P. IE11
