### ISSUE TITLE
Which browser versions are supported?

### ISSUE THREAD

**Issue by holgersindbaek** [fabiospampinato/cash#335]
The current version specifies that IE11 and upwards is supported, but what about Chrome, Firefox etc? What about mobile browsers?

**Comment by fabiospampinato** [comment]
"IE X+" usually means "all the modern browsers plus IE from version X onwards".

Roughly all browsers with support for the classList API (https://caniuse.com/#feat=classlist) should be supported.

We are not testing all browser versions against all OS versions though, here  the tested browsers are listed: https://github.com/fabiospampinato/cash/blob/b5cdf0461c693a47031d098ca35a13548218db93/karma.conf.js#L8-L82

**Comment by holgersindbaek** [comment]
Ok. Thank you for the clarification.
