### ISSUE TITLE
NewBie - $(document).ready(function() { } ); in  Cash ?

### ISSUE THREAD

**Issue by marcoczen** [fabiospampinato/cash#339]
Hi,

In JQuery, to ensure DOM is ready before we run scripts, we use;

``` $(document).ready(function() { some code here } ); ```

In Cash how do we do this ? Like -> https://github.com/fabiospampinato/cash/pull/4  ?
Dont seem to see this  in the doc. Sorry.

**Note** - new to cash. Came here after noticing that zepto  is 'dead'   and the fork is also 'dead'.  This project seems actively maintained. Great job.

**Comment by limonte** [comment]
> In JQuery, to ensure DOM is ready before we run scripts, we use;
> 
> `$(document).ready(function() { some code here } );`
> 
> In Cash how do we do this ?

Sure: https://github.com/fabiospampinato/cash#fnready-

**Comment by fabiospampinato** [comment]
You can just write: `$(function() { some code here } );`, it works the same and it's a bit cleaner.

**Comment by marcoczen** [comment]
Thank you.

So ...

$(document).ready(function() { some code here } );  
$(function() { some code here } );

Thank you. Got it.

**Comment by fabiospampinato** [comment]
Yes 👍 As a rule of thumb you can just use jQuery's docs instead, which are much better: https://api.jquery.com/

**Comment by marcoczen** [comment]
Thank you.
