### ISSUE TITLE
Why `mouseenter` delegate event handler is not firing? (but works with jquery)

### ISSUE THREAD

**Issue by m-ahmadi** [fabiospampinato/cash#341]
Hi,
Why [this](https://codepen.io/m-ahmadi/pen/PoPOwbW) isn't working? If I switch to `jquery` it will work though.

<details>
<summary>In case the pen has issues:</summary>

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/cash/7.0.1/cash.min.js"></script>
<!-- <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" crossorigin="anonymous"></script> -->

<ul style="background:red;">
  <li>a</li>
  <li>b</li>
  <li>c</li>
</ul>

<script>
$('ul').on('mouseenter','li', function () {
  alert('fired');
})
</script>
`

**Comment by fabiospampinato** [comment]
It looks like a bug 🤔

**Comment by krschroeder** [comment]
same issue, 'mouseenter' not working 😢

**Comment by TryHardDood** [comment]
@fabiospampinato @m-ahmadi 
It's working:
* Mouseenter: https://jsfiddle.net/hp8ezfg0/
* Mouseover: https://jsfiddle.net/drsq4jLg/

https://developer.mozilla.org/en-US/docs/Web/API/Element/mouseenter_event

**Comment by m-ahmadi** [comment]
Somehow it's not working in CodePen, but it works when I copy it into a `test.html` file.
<details>
<summary>test.html</summary>

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/cash/7.0.1/cash.min.js"></script>

<ul style="background:red;">
  <li>a</li>
  <li>b</li>
  <li>c</li>
</ul>

<script>
$('ul').on('mouseenter','li', function () {
  alert('fired');
})
</script>
```

</details>

@TryHardDood  At first I thought your version works because it's using `v7.0.3` but it even works with `v7.0.1` which was used in the first post of this issue,  so I guess something must be wrong with CodePen.

**Comment by TryHardDood** [comment]
@m-ahmadi I tried it on codepen and my versions are working.

Mouseenter: https://codepen.io/TryHardDood/pen/qBbORda
Mouseover: https://codepen.io/TryHardDood/pen/jOWbyPd

This will not work for some reason (it's not working on jsfiddle too):
```
$('ul').on('mouseenter','li', function () {
  alert('fired');
})
```

Probably because you need to use mouseover instead of mouseenter

**Comment by m-ahmadi** [comment]
> This will not work for some reason (it's not working on jsfiddle too):

Well then the issue is still there.  

Because when you do `$('ul li').on('mouseenter', ...)`, that's not a delegated event (you're adding a listener to every `<li>`) and there was no problem or issue with that in the first place.  

The issue is when you do `$('ul').on('mouseenter', 'li', ...)` and not on `mouseever` (which works fine)  but on `mouseenter`.

The reason I made this issue is that this works in `jquery` so using `mouseover` instead might be a quick fix, but I don't that's the answer here.

**Comment by TryHardDood** [comment]
@m-ahmadi Yeah you're right.

mouseover can be a quick workaround in this case however the problem exists with mouseleave too.

After a quick research I found this in jquery's source code, it seems like jquery use the mouseover/out events to make delegation work:
https://github.com/jquery/jquery/blob/3d62d5704989f17d3a20ae7521d52e9c8c60b4ee/src/event.js#L777

**Comment by fabiospampinato** [comment]
Fixed in v8! What an absolute mess of a bug, imagine my face when saw this: https://github.com/fabiospampinato/cash/commit/a66b43ed058edf31fcc4dfcc1f0fdf7a15dfb47a#diff-07b7d1177cdf432e3402964df5c32d69L111
