### ISSUE TITLE
fn.get() returns never[] in TypeScript 3.9.3

### ISSUE THREAD

**Issue by kasugaiasuka** [fabiospampinato/cash#344]
### Current behavior

package.json

```json
{
  "name": "temp2",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cash-dom": "^7.0.1",
    "typescript": "^3.9.3"
  }
}
```

tsconfig.json

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["DOM", "ESNext"],
    "strict": true,
    "esModuleInterop": true
  }
}
```

index.ts

```typescript
import $ from "cash-dom";

const cashObj = $("a"); // <- cashObj is Cash
const all = cashObj.get(); // <- all is never[]
const first = cashObj.get(0); // <- first is undefined
```

### Expected behavior

`all` is `EleLoose[]`, `first` is `EleLoose | undefined`.

FYI, this code works well in TypeScript 3.8.3.

**Comment by kasugaiasuka** [comment]
Ah, it must come from [an breaking change](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#intersections-reduced-by-discriminant-properties) in TS 3.9.

`type XXX = HTMLMarqueeElement & HTMLMediaElement` is collapsed to `never` because 
type of `HTMLMarqueeElement.loop` and `HTMLMediaElement.loop` is different.
This `never` spreads on `EleHTMLLoose` and `EleLoose`, so `fn.get()` returns never[].

**Comment by fabiospampinato** [comment]
🤔 On one hand this makes sense, our `EleLoose` type is pretty much impossible, on the other though being strict and requiring too much manual type checking, for a library like this, I don't think would be optimal. I'm not sure how we should react to this change.

**Comment by fabiospampinato** [comment]
It [looks like](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/aff20085570a404b20ad36f33d2df73b3ce0753a/types/jquery/v2/index.d.ts#L3364) jQuery is just returning `Element[]`, which isn't quite correct if that collection contains the `window` object for example. I can't think of a usable workaround for this that doesn't require too much manual type checking on the user side 🤔

**Comment by kasugaiasuka** [comment]
Yes, it's a correct but depressing change.

I can't think of a solution other than to change `get(): EleLoose[]` to `Ele[]`. Not cool.
