### ISSUE TITLE
Add release dates to the changelog

### ISSUE THREAD

**Issue by chocolateboy** [fabiospampinato/cash#348]
### Feature description

Add release dates to the [CHANGELOG](https://github.com/fabiospampinato/cash/blob/master/CHANGELOG.md).

### Feature motivation

It's good that there's a changelog which is kept up to date, but it's not very useful without dates.

From [Keep a Changelog](https://keepachangelog.com/en/1.0.0/#how): **How do I make a good changelog?**

>  The release date of each version is displayed.

**Comment by fabiospampinato** [comment]
@chocolateboy I don't care one bit about what "Keep a Changelog" thinks a changelog should look like. _Why_ do _you_ want this? In particular how do dates in changelogs make them go potentially from "not very useful" to "very useful"?

**Comment by chocolateboy** [comment]
Why *not* include dates (like the vast majority of changelogs do)? How does it hurt? What does it cost (it looks like [bump](https://github.com/fabiospampinato/bump) can easily add them)?

> I don't care one bit about what "Keep a Changelog" thinks

You'll find the same description/assumption in any [description of a changelog](https://en.wikipedia.org/wiki/Changelog#Format), or — indeed — pretty much [any](https://github.com/facebook/react/blob/master/CHANGELOG.md) [changelog](https://github.com/lodash/lodash/wiki/Changelog).

> Why do you want this?

I want to see what has changed *when*. It could be that the project is dead and that the last change/release was years ago. Alternatively, it could show that a project is being actively maintained. Or I might want to see how the project has evolved over time. Or troubleshoot a breaking change.

All of this becomes tedious guesswork/sleuthing if the changelog (AKA **history**) cryptically omits the most obvious and salient property of each release: *when* it occurred.

**Comment by fabiospampinato** [comment]
> Why not include dates (like the vast majority of changelogs do)? How does it hurt? What does it cost (it looks like bump can easily add them)?

I'm not making that argument 🤷‍♂️

Personally other than knowing "when was the last commit?" I don't really care when past releases occurred.

> You'll find the same description/assumption in any description of a changelog, or — indeed — pretty much any changelog.

Following others without understanding could be dangerous, with this mentality born a couple thousand years ago (or gosh, maybe even today) you'd believe that tornados appear when the god of wind farts or something.

> I want to see what has changed when. It could be that the project is dead and that the last change/release was years ago. 

The answer to "When was the last commit?" is usually what you want here, just looking at when the last release occurred might mislead you if releases happen in long cycles.

> Alternatively, it could show that a project is being actively maintained. 

I think looking at the commits history might be better for that, but I guess the changelog should probably give you enough information about that too 🤔 

> Or I might want to see how the project has evolved over time. Or troubleshoot a breaking change.

🤔 

> All of this becomes tedious guesswork/sleuthing if the changelog (AKA history) cryptically omits the most obvious and salient property of each release: when it occurred.

I would argue the most salient piece is what the breaking changes are, if any.

---

It seems like on balance it might be worth adding release dates to the changelog 👍

**Comment by chocolateboy** [comment]
> The answer to "When was the last commit?"

Commits != releases. There may have been many commits to a project, sometimes stretching over [years](https://github.com/cheeriojs/cheerio/releases/tag/1.0.0-rc.3), since the last release.

"Check the [GitHub] repo to figure out the change" is useless if you're trying to troubleshoot an issue in production in a dependency in your `node_modules` folder. Or if GitHub is down. Or if the release notes aren't descriptive etc.

**Comment by chocolateboy** [comment]
> I would argue the most salient piece is what the breaking changes are, if any.

I would argue that the date matters here more than ever, e.g. dropping support for an EOL Node.js version is a dramatically different change than dropping support for a maintained Node.js version (e.g. because it doesn't support a new feature), even though both could be breaking changes. The difference is entirely down to *when* that change was made.

**Comment by fabiospampinato** [comment]
Done
