### ISSUE TITLE
Deprecated jQuery.isArray

### ISSUE THREAD

**Issue by Daijobou** [fabiospampinato/cash#353]
Its not a bug, but maybe unnecessary.

$.isArray is deprecated
https://github.com/fabiospampinato/cash#isarray-
http://blog.jquery.com/2017/03/16/jquery-3-2-0-is-out/

$.isFunction is deprecated
https://github.com/fabiospampinato/cash#isfunction-
https://api.jquery.com/jQuery.isFunction/

**Comment by fabiospampinato** [comment]
We'll just try to align with v4 once that's released, potentially removing those methods.
