### ISSUE TITLE
Version number in dist files

### ISSUE THREAD

**Issue by Daijobou** [fabiospampinato/cash#354]
Can you add please the version number in /dist/cash.min.js and /dist/cash.js? 
Alternatively in filename?

Currently you save the file and after months you have no clue what version this was.

**Comment by fabiospampinato** [comment]
Maybe in the copyright comment we could link to the commit that changed the version number 🤔 I'm not sure about this though, the size of `cash.min.js` matters to us and linking to the bump commit doesn't _really_ add anything to the library itself, other than weight, it's more some kind of metadata about it.

I'd say if you are happy with having the version number in the file name you can do that yourself right now. 

In the meantime I'll keep this issue open to see if people want this to be implemented.

**Comment by limonte** [comment]
> Currently you save the file and after months you have no clue what version this was.

You're using the wrong way for installing dependencies. The issue in the issue description is caused by the fact you don't use the package manager (npm, yarn).

What you're asking is to add more bytes to EVERYONE because you can't use the package manager. How about learning how npm works? :)
