### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pseudos' of undefined

### ISSUE THREAD

**Issue by Daijobou** [fabiospampinato/cash#355]
I wanted to see if cash can replace the currently used jquery version. Unfortunately I get an error when integrating jqueryUI (widget):
**Uncaught TypeError: Cannot read property 'pseudos' of undefined**
```
	// Create selector for plugin
	$.expr.pseudos[ fullName.toLowerCase() ] = function( elem ) {
		return !!$.data( elem, fullName );
	};
```
Source https://github.com/jquery/jquery-ui/blob/master/ui/widget.js#L68

Is this a bug or is it not planned to support or is here a extension?

**Comment by varunsridharan** [comment]
@Daijobou well jQuery has its own Selector engine which means it provides developers with option to use CSS Selectors such as `:input`, `:hidden` ,`:visible` ( https://api.jquery.com/category/selectors/jquery-selector-extensions/ ) and currently its not supported by Cash as its not natively support by javascript itsef.

**Comment by fabiospampinato** [comment]
The way jQuery allows you to extend how selectors work is not supported and won't be supported.
