### ISSUE TITLE
some thought to work with .map and .find and cash

### ISSUE THREAD

**Issue by simonjoom** [fabiospampinato/cash#357]
Hi, 
with the last cash:

I ve got some issue because i wanted to use [].find (vanilla javascript) with $.map (cash)
problem is that cash has no 'find' with a callback only on selector:

so we cannot do that unfortunately :
$(items).find((i,el)=>el.width>0)

i tried
$(items).map((i,el)=>el.get()) to get a map of domelement but without success

$.map always return a instance of cash ..

i did create a $.maptoDom (just removed the creation on cash instance of $.map)
 to have my array of domelement that i can use with some vanilla javacript like [].find

so now to have $(items).find((i,el)=>el.width>0)  I did $(items).maptoDom((i,el)=>el).find(el=>el.width>0)

Maybe some implementation should be realized

**Comment by varunsridharan** [comment]
@simonjoom i am not wrong CASH Currently dose not support Objects like jquery. it can handle only DOM Objects.

**Comment by simonjoom** [comment]
it's exactly to retrieve dom object from $.Map who is impossible ! it s why it's a pity that we cannot access dom on map

**Comment by fabiospampinato** [comment]
I think you want to use `$.fn.get`, which when called with no arguments just converts the collection to a regular array.

**Comment by simonjoom** [comment]
Ah ok! so $.get($.map(array(dom)))===array(dom)
i thought $.get work only for element not for array

**Comment by fabiospampinato** [comment]
`$.fn.get`, not `$.get` (which we don't implement).`

```
$eles.get ().find ( ele => /* something here */ )
```

**Comment by simonjoom** [comment]
yes it's seems more logical to me now.

yeah sorry i mistaken when i wrote. so  you confirm 
$eles.get ().find ( ele => /* something here */ )
that here ele is a dom element not a cash element

**Comment by fabiospampinato** [comment]
Yeah, but you don't need me to confirm that, try it.
