### ISSUE TITLE
setting a data attribute on an element adds extra quotes around string

### ISSUE THREAD

**Issue by krschroeder** [fabiospampinato/cash#358]
### Current behavior

```javascript 
$('h1').eq(0).data('foo','bar')
//outputs <h1 data-foo=""bar"">Header Text</h1>
```
### Expected behavior

```javascript 
$('h1').eq(0).data('foo','bar')
//outputs <h1 data-foo="bar">Header Text</h1>
```

**Comment by fabiospampinato** [comment]
It's not extra, otherwise you wouldn't be able to set `"1"` and get `"1"` back rather than `1`.

This is mentioned in the migration guide: https://github.com/fabiospampinato/cash/blob/master/docs/migration_guide.md#data

**Comment by fabiospampinato** [comment]
If you want `$.fn.data` to behave` like `$.fn.attr` you should just use `$.fn.attr`

**Comment by krschroeder** [comment]
Yeah I just used attr. Thanks for the fast response, forgot about that guide!
