### ISSUE TITLE
toggleClass not working with Bulma css ?

### ISSUE THREAD

**Issue by camillo777** [fabiospampinato/cash#359]
Chrome Version 86.0.4240.111 (Official Build) (x86_64)
Latest Cash js 8.1.0
Latest Bulma CSS 0.9.1

# Current behavior

See here simple button with toggleClass and Bulma css.

https://jsfiddle.net/aswn3o7f/

How to reproduce:

- Click on the button: nothing happens.
- Click on the 2nd button, the first button refresh the GUI with the new class, but the 2nd button does not change.
- Click on the first button to apply change to the 2nd button as well.

Button is not refreshing with the new class "is-outlined".
Button refresh with new class only if i click on another button (GUI refresh?)

### Expected behavior

Button should change css to "is-outlined" and look and feels should be reflected in the browser

**Comment by fabiospampinato** [comment]
> Button should change css to "is-outlined" 

Which is happening, you should check that via the devtools.

> and look and feels should be reflected in the browser

Not a problem with cash-dom, you are experiencing some unexpected behavior of Bulma.

**Comment by camillo777** [comment]
Thanks, anyway awesome lib, i will let you know
