### ISSUE TITLE
Equivalent to jQueries $(selector).on('click')

### ISSUE THREAD

**Issue by hellokvn** [fabiospampinato/cash#360]
jQueries offers 2 ways to catch e.g. click events.

Static way: $(selector).click()
Dynamically: $(selector).on('click)

The dynamically way catches events of re-rendered html contents which e.g. was created by an ajax request. Does CashJS has an equivalent to that?

CashJS's $(selector).on('click') function ignored re-rerendered html content.

**Comment by fabiospampinato** [comment]
I'm pretty sure there's no static/dynamic distinction like that, `.click` is just a shorthand.

Shorthands like that don't make sense in a project that values being as small as possible, so if you want them you'll have to reimplement them yourself (reference implementation: https://github.com/fabiospampinato/cash/blob/master/src/extra/shorthands.ts).

**Comment by fabiospampinato** [comment]
If you want to catch events on nodes not available when the event handler got attached what you need is event delegation, which cash supports.
