### ISSUE TITLE
Jquery 1.x to Cash 8.x

### ISSUE THREAD

**Issue by sbandaru08** [fabiospampinato/cash#365]
Quick Info: We are currently using jQuery and want to move away from it and use cash. I have listed all the 

**jQuery:**
- Currently, We are using jQuery version 1.9.1 current version.

Library | Current Version| Release Date | New Version | Release Date
-- | -- | -- | -- | --
jQuery | 1.9.1 | 4-Feb-2013 | 3.5.1 | 4-May-2020

**jQuery Plugins:** 

Plugins | Version
-- | --
jQuery-ui | 1.10.3
qtip2 | 2.1.1
jquery.colorbox | 1.4.27
jquery.multiselect | 1.14pre
jQuery.mouseWheel | 3.0.6
jquery.mCustomScrollbar | -

Can i use cash to migrate from jQuery directly and should i be concerned about any old deprecated functions like:
- .bind()
- .delegate()
- :eq() Selector
- jQuery.browser
- jQuery.now()
- jQuery.proxy()
- jQuery.support
- jQuery.trim()
- .load()
- .size()
- .toggle()
- .unbind()
- .on()

**Comment by fabiospampinato** [comment]
It'd improbably hard to move to Cash when you are using heavy stuff like jQuery UI. I'd try to move to jQuery 2, then jQuery 3, then jQuery 3 slim, then to Cash and see what breaks. Most probably some significant rewrites on your side will be needed.
