### ISSUE TITLE
Ensuring `$.fn.html` executes scripts

### ISSUE THREAD

**Issue by vovayatsyuk** [fabiospampinato/cash#366]
Just found such kind of inconsistency.

```js
// script is not executed
$('body').html('<script>alert(1)</script>');

// script is excuted
$('body').html('').append('<script>alert(1)</script>');
```

**Comment by vovayatsyuk** [comment]
I thought I will able to fix it by replacing the following code:

https://github.com/fabiospampinato/cash/blob/master/src/manipulation/html.ts#L19-L25

```js
  return this.each ( ( i, ele ) => {

    if ( !isElement ( ele ) ) return;

    ele.innerHTML = html;

  });
```

with:

```js
return this.empty().append(cash.parseHTML(html));
```

But it fails in `.html(0)` test.

**Comment by vovayatsyuk** [comment]
I can prepare PR with the following changes to [html.ts](https://github.com/fabiospampinato/cash/blob/master/src/manipulation/html.ts) if I did that correctly and if you believe this should be fixed:

```diff
 // @require core/cash.ts
 // @require core/type_checking.ts
-// @require collection/each.ts
+// @require core/variables.ts
+// @require collection/filter.ts
+// @require ./append.ts
+// @require ./empty.ts
+// @require ./text.ts
 
 interface Cash {
   html (): string;
 
   if ( isUndefined ( html ) ) return this;
 
-  return this.each ( ( i, ele ) => {
-
-    if ( !isElement ( ele ) ) return;
-
-    ele.innerHTML = html;
-
-  });
+  if ( htmlRe.test ( html ) ) {
+
+    this.filter ( ( i: number, ele: EleLoose ) => isElement ( ele ) ).empty ().append ( html );
+
+  } else {
+
+    this.text ( html );
+
+  }
 
+  return this;
 }
 
 fn.html = html;
```

**Comment by fabiospampinato** [comment]
First of all how does jQuery behave under the same scenario? Cash is general strives to align with that as much as possible.

**Comment by vovayatsyuk** [comment]
jQuery executes scripts passed to `.html` method. Just tried at [jquery.com](jquery.com) in the browser console:

```
jQuery('body').html('<script>alert(1)</script>');
```

Here is a link to jquery's implementation: https://github.com/jquery/jquery/blob/main/src/manipulation.js#L373-L402

**Comment by fabiospampinato** [comment]
Same for append?

**Comment by vovayatsyuk** [comment]
Append is working fine in Cash :). Scripts are executed.

**Comment by fabiospampinato** [comment]
But is that what jQuery does too? Correctness is alignment with jQuery basically.

**Comment by vovayatsyuk** [comment]
Yes, all jQuery's methods that accepts html will execute scripts.

https://api.jquery.com/html/:

> By design, any jQuery constructor or method that accepts an HTML string — jQuery(), .append(), .after(), etc. — can potentially execute code. This can occur by injection of script tags or use of HTML attributes that execute code (for example, <img onload="">). Do not use these methods to insert strings obtained from untrusted sources such as URL query parameters, cookies, or form inputs. Doing so can introduce cross-site-scripting (XSS) vulnerabilities. Remove or escape any user input before adding content to the document.
