### ISSUE TITLE
How do I highlight text within HTML?

### ISSUE THREAD

**Issue by Qara-Penimah** [fabiospampinato/cash#367]
How to dynamically highlight keywords within HTML content.

**Comment by vovayatsyuk** [comment]
This library is not about highlighting. it's about collections and working dom.

p.s. You can use [mark tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark) to highlight something at the page.

**Comment by fabiospampinato** [comment]
Try mark.js (https://markjs.io/) or ask google.
