### ISSUE TITLE
Plugins repository/database

### ISSUE THREAD

**Issue by markgarbers** [fabiospampinato/cash#368]
Perhaps related to the ticket referencing creating a documentation site, but it would be really handy to have a list of extensions people have created for Cash.

It'd be a great way to avoid writing extensions that other contributors may already have created.

**Comment by fabiospampinato** [comment]
I think something like that could be useful, but who's going to write it?

Happy to add something like that to Cash's repo if somebody can manage to compile a nice list with 10~20 items, where each item is a library that works with Cash (even better if it works with jQuery too) and the list contains it's name, a short description, a link to its homepage/documentation/repo, and a link to a codepen using that library with Cash.

**Comment by fabiospampinato** [comment]
Closing as I don't see this happening.
