### ISSUE TITLE
Unsupported jQuery selectors

### ISSUE THREAD

**Issue by X25guru** [fabiospampinato/cash#370]
I'm replacing jquery with cash on a fairly complex site and the biggest thing that keeps biting me is the generic error messages when using an unsupported selector such as :input or :selected. I get the error:

 "The string did not match expected pattern" in querySelectorAll

jQuery of course silently returns no match for unknown selector patterns. So I have a couple of suggestions:

1) It would be very useful for migrations to detect common, unsupported jquery selectors and provide some sort of debug trace ie ":input not supported by cash"
2) catch this error and mimic jquery and simply return no match for this type of error

**Comment by fabiospampinato** [comment]
By design only the selectors the browser supports are supported.

- There's no migration plugin and no intention to write one.
- There's no intention to mimic jQuery or silence these kinds of errors.
