### ISSUE TITLE
`$.trigger`/`$.on` compatibility with jQuery

### ISSUE THREAD

**Issue by gabrielfin** [fabiospampinato/cash#374]
### Current behavior

```js
$('foo').on('bar', (e, a, b, c) => console.log(a, b, c) );
$('foo').trigger('bar', [1, 2, 3]);
```
Outputs:
```js
[1, 2, 3] undefined undefined
```

### Expected behavior

With jQuery, the output is:
```js
1 2 3
```

According to https://api.jquery.com/on/
> If an array was passed to the second argument of .trigger() or .triggerHandler(), each element in the array will be presented to the event handler as an individual parameter.

I know Cash is not meant to be used as a drop-in replacement for jQuery, but I'm trying to make it work with a third party plugin that is using this "feature" extensively. Is there any way to add support for it?

**Comment by gabrielfin** [comment]
Nevermind. I just saw that it's on the migration guide as a limitation.

**Comment by fabiospampinato** [comment]
Maybe this should be aligned with jQuery, I don't remember exactly why there's this difference, maybe this is something I kind of inherited from the previous implementation of Cash.
