### ISSUE TITLE
Is it possible to load Cash in "noconflict mode"

### ISSUE THREAD

**Issue by bigb06** [fabiospampinato/cash#375]
We develop a small JS widget that can be load on any website
Until now we use jQuery if it is already loaded by website, or we load our version with noconflict mode.

I'm very interested to embed cash directly in our widget, but can we load it in "noconflict mode" ?
`jQuery = window.jQuery.noConflict(true);`
If another JS library already defined $ can we load cash to use another name ? 

Thanks !

**Comment by fabiospampinato** [comment]
> If another JS library already defined $ can we load cash to use another name ?

Sure, there's no "noConflict" method provided though, so you'll have to do something like this:

```js
const _prev$ = window.$;
// Load cash now...
const cash = window.$;
window.$ = _prev$;
```

**Comment by bigb06** [comment]
Thanks !
