### ISSUE TITLE
Cash-Website shows a scary 1.0.0 version info 

### ISSUE THREAD

**Issue by iJungleboy** [fabiospampinato/cash#377]
### Current behavior

The website of cash: https://kenwheeler.github.io/cash/ shows "Get v1.0.0" which doesn't instill confidence. I believe this is wrong and should be fixed. 

![image](https://user-images.githubusercontent.com/5321186/122967753-16b7ef00-d38b-11eb-8909-85805c9f4205.png)

**Comment by fabiospampinato** [comment]
I don't control that website, so that's neither official anymore nor in any way up to date.
