### ISSUE TITLE
$("svg").attr("width", "1.5rem") on SVG elements gives a warning

### ISSUE THREAD

**Issue by leoplaw** [fabiospampinato/cash#384]
### Current behaviour

$("svg").attr("width", "1.5rem")
produces warnings. 
When there are many svg elements on the page, this impacts performance.

### Expected behaviour

Should produce no warnings, as the size unit "rem" is valid and actually works in SVG elements.

**Comment by dheerapat** [comment]
working just fine for me.

This is before $("svg").attr("width", "1.5rem")
![svg-github-before](https://user-images.githubusercontent.com/61280196/167867607-73ae34df-2fe2-444b-a7fc-915ddaa06f3e.png)

And after
![svg-github-after](https://user-images.githubusercontent.com/61280196/167867802-78bfb648-6a62-4d81-9e19-6d67c637c4c7.png)

**Comment by fabiospampinato** [comment]
Closing for lack of a repro.
