### ISSUE TITLE
Find by ID when context is not in documemt

### ISSUE THREAD

**Issue by millerrafi** [fabiospampinato/cash#385]
Related to #270

I'm attempting to migrate a codebase from jQuery and I have code like this, manipulating some HTML before it is added to the DOM:

```
let div = document.createElement("div");
div.innerHTML = '<span id="foo">Foo</span>';

$("#foo", div).text('Bar');
```

[Example on codesandbox](https://codesandbox.io/s/admiring-wind-pc1mc?file=/src/index.js:49-158)

This code is working with jQuery but not with Cash. 

A quick local test shows that replacing `ctx.getElementById(selector.slice(1))` with `ctx.querySelector(selector)` in cash.esm.js resolves this for me. I think the performance difference would be negligible?

**Comment by fabiospampinato** [comment]
This should be fixed 🤔 

It may be best to wrap that in a check for [isConnected](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected). I wouldn

**Comment by fabiospampinato** [comment]
This should be fixed 🤔 

It may be best to wrap that in a check for [isConnected](https://developer.mozilla.org/en-US/docs/Web/API/Node/isConnected). I wouldn't want to sacrifice being able to use getElementById, which is much faster than querySelector.

**Comment by millerrafi** [comment]
Hey, I can submit a PR if you would like with `isConnected`.

```ts
      eles = idRe.test(selector)
        ? (ctx as Element).isConnected
          ? (ctx as Document).getElementById(selector.slice(1))
          : (ctx as Element).querySelector(selector)
        : htmlRe.test(selector)
        ? parseHTML(selector)
        : find(selector, ctx);
```

Although, a quick test suggests that `isConnected` + `getElementById` might not be faster than `querySelector`. I heard once that browsers optimize querySelector when it gets an ID.

Running this test in my console on this page

```js
console.time('qs')
i = 1e7;
while (i--) document.querySelector('#issue_title')
console.timeEnd('qs')

console.time('gebi')
i = 1e7;
while (i--) document.isConnected && document.getElementById('issue_title')
console.timeEnd('gebi')
```
