### ISSUE TITLE
Misleading documentation about the size of the library

### ISSUE THREAD

**Issue by jcubic** [fabiospampinato/cash#389]
The documentation says that Cash is a small library 8kB in size but in fact, it's 15.7kB in size. 

https://github.com/fabiospampinato/cash/blob/master/dist/cash.min.js

And you don't show the size of Gziped data unless you specify that the size is gzipped otherwise is misleading.

I've spent a while debugging my code where I'm trying to take a few things from jQuery and cash and I was testing multiple things because I thought that my code import whole jQuery. The output size that I've got was 23kB.

**Comment by fabiospampinato** [comment]
I'm confused, everything you said about Cash, except that 15.7kb figure, is wrong.

This in front and center in the readme:

<img width="553" alt="Screen Shot 2022-01-04 at 22 11 30" src="https://user-images.githubusercontent.com/1812093/148130890-a2cca78f-c4de-4d74-89b7-3c89b87a3330.png">

- There's no mention of "8kb" anywhere in the readme.
- It clearly says that Cash is about 6kb minified and gzipped.
- it clearly says that Cash is about 16kb just minified.
- All figures are very clearly labeled in what they are measuring (unminified, minified, minified + gzipped).

**Comment by jcubic** [comment]
There is on the website, maybe it's not your weebsite. But if you google Cash JavaScript library it show up as first result. Rigth now it's second (at list when I tested).

https://www.google.com/search?hl=pl&q=cash%20javascript%20library

I just assumed it's an official website if it's in Google, I usually go to the website, not to GitHub. If it's not your website maybe you should ask that person to take it down.

**Comment by fabiospampinato** [comment]
> I just assumed it's an official website if it's in Google

No offense intended but that's something I'd expect my mom to say.

>  usually go to the website, not to GitHub.

That's only safe if you got the link of the website from github, and Cash's repo doesn't link to that.

> If it's not your website maybe you should ask that person to take it down.

I already did long ago, but then again it's not my website, I don't have any control over it, I can't do anything if my emails get lost in the inbox.

The website should redirect to the repository or get deleted, but I can't do it.

**Comment by jcubic** [comment]
> > I just assumed it's an official website if it's in Google

> No offense intended but that's something I'd expect my mom to say.

I simply didn't notice that it's not an official website, I had to write something to explain, why this was the only thing that came into my mind.

I've noticed a weird thing, this page:

https://github.com/kenwheeler/cash/

redirect to your repo, I would contact GitHub support since the Gh-Page looks like abanodend. Or some kind of error on part of GitHub.

**Comment by fabiospampinato** [comment]
The website at https://kenwheeler.github.io/cash/ basically talks about v1 of Cash, which is completely different from the current version.

**Comment by fabiospampinato** [comment]
Let me asked them for this, maybe it's more likely they'll do it if I ask them.

**Comment by fabiospampinato** [comment]
I contacted Ken 2 weeks ago, no reply. I've just contacted github too. I'll report back when I'll hear some updates.

**Comment by jcubic** [comment]
@fabiospampinato thanks for the update. Just a tip you can get [cash.js.org](https://cash.js.org/) subdomain for free and add it to GitHub pages.

**Comment by fabiospampinato** [comment]
@jcubic github said they can't change things of other users or contact them on my behalf. Ken said it would set up the redirect but nothing has changed as of yet.
