### ISSUE TITLE
replaceWith() doesn't work on <html> node

### ISSUE THREAD

**Issue by aimeos** [fabiospampinato/cash#392]
### Current behavior

```
$("html").replaceWith(document.createElement("html"));
```

Results in this error:

```
DOMException: Failed to execute 'insertBefore' on 'Node': Only one element on document allowed.
```

### Expected behavior

Replaces the `<html>` node by a new one.

**Comment by fabiospampinato** [comment]
This is tricky to fix cleanly 🤔 For the time being it would be better to avoid using `replaceWith` in this case, just detach the `html` element first and attach the next elements in a separate step.
