### ISSUE TITLE
Bootstap modal events not working

### ISSUE THREAD

**Issue by LazeMSS** [fabiospampinato/cash#393]
When adding an on/one event handler on a bootstrap modal the event is never triggered:
```
$('#modal').on('hidden.bs.modal', function(){
         console.log('hidden');
});
```

Using native js it works:
```
document.getElementById('modal').addEventListener('hidden.bs.modal', function (event) {
         console.log('hidden');
})
```

**Comment by LazeMSS** [comment]
Ahh it might be duplicate of https://github.com/fabiospampinato/cash/issues/379

**Comment by fabiospampinato** [comment]
> Ahh it might be duplicate of https://github.com/fabiospampinato/cash/issues/379

It looks like, yeah.
