### ISSUE TITLE
Event properties should be settable

### ISSUE THREAD

**Issue by alecpl** [fabiospampinato/cash#400]
When using Bootstrap v5 I get TypeError: setting getter-only property "delegateTarget" errors. It is because the property in cash-dom has no setter, but Bootstrap's code is setting it.

More info: https://github.com/twbs/bootstrap/issues/36207

**Comment by fabiospampinato** [comment]
🤔 in general we are just provided whatever event object the browser gives us, so if you want that to work differently you'd have to ask them about it.

In particular I'm not sure if `delegateTarget`, which cash is setting, should really be settable, like these are properties of the event, their value shouldn't depend on arbitrary code, right? It'd guess Bootstrap is setting that in case that's not set already maybe, in which case I'd argue they are setting it wrong, they should be setting it with code similar to ours.

**Comment by fabiospampinato** [comment]
Closing as not a issue on our end.
