### ISSUE TITLE
Collection doesn't pass unknown method calls to items

### ISSUE THREAD

**Issue by aimeos** [fabiospampinato/cash#403]
### Current behavior

This raises a type error:
```
$('form').submit();
```

`$('form')` returns a collection which doesn't know the `submit()` method and in this case, the `submit()` method should be called on the the elements of the collection instead. This must be done for all unknown methods to comply to jQuery behavior.

### Expected behavior

Form should be submitted.

**Comment by aimeos** [comment]
In terms of code size, passing unknown methods to the DOM elements in the collection instead of implementing each missing method would be a good idea, isn't it?

**Comment by fabiospampinato** [comment]
Maybe, but I see only downsides with that basically, first of all the collection would have to become a Proxy, which would slow everything down a bit, and it's not supported by IE11 (though support for that can just be dropped).

**Comment by aimeos** [comment]
IE11 isn't support by cash-dom AFAIK so this should be no problem but I don't know how much using of the Proxy object will slow down execution of the code.

**Comment by fabiospampinato** [comment]
IE11 is supported at the moment.

**Comment by fabiospampinato** [comment]
Closing as jQuery doesn't work like that, nor should Cash.
