### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by omelao** [fabiospampinato/cash#406]
I want to contribute with some functions I wrote, but there are a lot of errors...

![image](https://user-images.githubusercontent.com/19227697/192394475-a459c4c6-9c24-4164-88d9-5e7f11ebbdaf.png)

**Comment by fabiospampinato** [comment]
Type-checking errors don't prevent the compiled code from being emitted. 

They are there kind of on purpose, I went through all of them and they are fine, this library is under stringent bundle size constraints so making TS happy would introduce a bunch of unnecessary code that would make us break our budget.

**Comment by fabiospampinato** [comment]
Btw new functions aren't necessarily accepted here, like if you add a 250b function I'd like first of all to see those 250b shaves from somewhere else so that the bundle size doesn't grow.

**Comment by omelao** [comment]
It's just [when](https://github.com/fabiospampinato/cash/compare/master...omelao:cash:add-when) and [scroll](https://github.com/fabiospampinato/cash/compare/master...omelao:cash:add-scroll) functions.
