### ISSUE TITLE
Append Options to Select Returns Empty Options

### ISSUE THREAD

**Issue by xbaha** [fabiospampinato/cash#407]
In the below example working on JQuery, I haven't found any migration docs on how to append options to select-box
In the SelectBox HTML there are empty <option></option> , the values value and text were not appended.

Any idea?
```
      $.each(model, function (i, item) {
        $("#" + slectBox).append(
          $("<option>", {
            value: item.id,
            text: item.id,
          })
        );
```

**Comment by fabiospampinato** [comment]
That particular function signature is not supported, you should rewrite it as "$(html).attr(attributes)"
