### ISSUE TITLE
Why use cash over browser API?

### ISSUE THREAD

**Issue by Sleepful** [fabiospampinato/cash#409]
I can see why people used jQuery back in the day.
I can see why people would want to use a modern jQuery if they are already accustomed to the library.
But I have never been a jQuery user, I was wondering if you would be so kind to tell me why I should (or should not) use this library over the standard browser API. 
To me, the newbie eye, $cash looks like the browser API with slightly shorter function names. Please correct me.
Thanks.

**Comment by fabiospampinato** [comment]
You probably shouldn't use this, but keep in mind that browser equivalent APIs don't exist for everything (like namespaced events) and they certainly can be less convenient to use.

**Comment by Sleepful** [comment]
@fabiospampinato as someone taking a look to see if I would like to use cash over the standard APIs, would be nice to have a little document describing the APIs that cash brings which don't have a browser equivalent. E.g. I did not know `namespaced events` were a cash feature and I did not find any sort of explanation on what they do from the README.
