### ISSUE TITLE
Non-existent test command in contributing guidelines

### ISSUE THREAD

**Issue by LeoDog896** [fabiospampinato/cash#411]
It seems that your contributing guidelines are outdated:

> 5. Automatically rerun the tests whenever a change is made: `npm run test:watch`.

The `test:watch` task no longer exists but is still referenced in the jquery reverse tests:
> `"test:jquery:reverse": "npm run test:jquery:init && npm run test:jquery:reverse:build && npm run test:watch",`

Some clarification on how to properly test cash for contributing would be great!

**Comment by fabiospampinato** [comment]
Oh right, I'll get that fixed 👍 

Basically it's an `npm run dev` to keep building on changes, `npm run test` to open the test page, and `npm run prepublishOnly` to do everything automatically once.

**Comment by LeoDog896** [comment]
alright, thanks for the clarification!

I was also about to edit it but I also noticed that on a fresh clone, `tsc` is doing type checking in the `dist` folder as well.

**Comment by LeoDog896** [comment]
> Is it 🤔 Anyway you'll see a million type errors, because they don't actually point at anything worth addressing at the type level, but addressing them would increase the size of this library.

I think that may be the case - all it's doing is needlessly type checking the generated cash.esm.ts file:

(from logs):
```
dist/cash.esm.ts:181:27 - error TS2339: Property 'nodeType' does not exist on type 'unknown'.

181   return !!value && value.nodeType === 3;
```

**Comment by fabiospampinato** [comment]
I've updated the contribution guide.

**Comment by fabiospampinato** [comment]
> tsc is doing type checking in the dist folder as well 

Ah, that's because I'm stitching the source files with a custom program first, so tsc is not _also_ checking the dist folder, it's _only_ checking the dist folder.
