### ISSUE TITLE
Setting attr "disabled" to true causes parse error

### ISSUE THREAD

**Issue by codepilotsf** [fabiospampinato/cash#413]
### Current behavior
`$('#my-button').attr('disabled', true)` 

fails with error:
```
SyntaxError: missing ) after argument list
    at Function (<anonymous>)
    at HTMLFormElement.handler (http://localhost:8080/script/zen.js:296:11)
```

Use `.attr` or `prop` to try to set `disabled` to `true` on a button element.

### Expected behavior

Button should become disabled without error.

**Comment by fabiospampinato** [comment]
It looks like the error is in your code, not in Cash?

If you can provide a repro I'll reopen the issue.
