### ISSUE TITLE
How to load an html string into Cash?

### ISSUE THREAD

**Issue by taji** [fabiospampinato/cash#414]
Taking from the documentation, I'd like to load an html string into cash and parse it.  

I have the following code: 

~~~<script src="https://cdnjs.cloudflare.com/ajax/libs/cash/8.1.3/cash.min.js"></script>
<script>
  $(function () {
    let htmlText =`
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>title</title>
    <link rel="stylesheet" href="style.css">
  </head>
  <body>
    <span id="hello">HELLO</span>
    <!-- page content -->
  </body>
</html>
`;
    let helloText = $(htmlText).find('span#hello').text();
    console.log('helloText: ', helloText);    
  });
</script>
~~~

However, the helloText string always returns undefined.   Is it possible to do what I am attempting with cash?

**Comment by taji** [comment]
For context: I'm referring to this call here: 

![image](https://user-images.githubusercontent.com/702031/222143962-46cd8e18-9672-4b23-b4eb-9501020a95c8.png)

**Comment by fabiospampinato** [comment]
It works like [that](https://playground.solidjs.com/anonymous/91ad1c50-da9b-4126-b5d0-e46373acadf5), but it parses HTML by setting .innerHTML on some element, so this doesn't work for parsing full-blown HTML with doctype and <html> tags and stuff.


It [doesn't seem](https://playground.solidjs.com/anonymous/d78cbdf0-1bce-44dc-8406-ca76229e056b) to work as you intended in jQuery either. So I guess we probably shouldn't make this work in Cash.

I'd recommend using DOMParser.

**Comment by taji** [comment]
Thanks :)
