### ISSUE TITLE
$.data(key, value) places too many double quotes

### ISSUE THREAD

**Issue by yannik-b** [fabiospampinato/cash#426]
### Current behavior

When trying to do 

```js
let colorMode = 'dark';
$('html').data('bs-theme', colorMode);
```

the result in the DOM looks like this: 

```html
<html data-bs-theme=""dark"">
```

### Expected behavior

The attribute should only have one pair of double quotes, like this:

```html
<html data-bs-theme="dark">
```

**Comment by fabiospampinato** [comment]
That's on purpose and documented in the migration guide: https://github.com/fabiospampinato/cash/blob/master/docs/migration_guide.md#data
