### ISSUE TITLE
Should this be a `!==` ?

### ISSUE THREAD

**Issue by cyfung1031** [fabiospampinato/cash#430]
https://github.com/fabiospampinato/cash/blob/ff807211dddbe1a63dd9e3d1dcbba0e2be97f8f0/src/core/pluck.ts#L26

Is this a typo?  Should it be `while ( val !== null ) {`?

#### File Link
https://github.com/fabiospampinato/cash/blob/master/src/core/pluck.ts

**Comment by fabiospampinato** [comment]
no when you do a `!= null` check that's a shorthand for `!== null && !== undefined`.

**Comment by cyfung1031** [comment]
> no when you do a `!= null` check that's a shorthand for `!== null && !== undefined`.

``` 
while ( val != null ) {
```

can be simplified to

```
while ( val ) {
```

**Comment by fabiospampinato** [comment]
That performs a different check though 🤔 Worth a second look to see if that would work for us though.
